### ISSUE TITLE
can i host it on hostinger ? and can you make a tutorial to setup this ? it will be very helpfull for anyone who is interested in it

### ISSUE THREAD

**Issue by arpitcheeta** [huy232/Unime#37]

**Comment by huy232** [comment]
I haven't tried Hostinger so I really don't know about it, but this is just a frontend of the project. I have my private backend, so you can probably clone this project to your local and try to use it. But if you deploy it to another domain, you'll get CORS block.

**Comment by owen786** [comment]
www.anime-subth.net
