### ISSUE TITLE
Website(Anime Not Playing)

### ISSUE THREAD

**Issue by ILikeW** [huy232/Unime#44]
Stuck on loading anime...

**Comment by huy232** [comment]
@ILikeW What happens, can you tell me more detail? Like, which episode, which anime, or what happened, I find it working normally at my side.

**Comment by ILikeW** [comment]
Like any anime I try to watch, I click on the episode but it doesn't play its just stuck on "Loading Anime" (I'm using website verison)

**Comment by huy232** [comment]
@ILikeW That's weird, I'm currently watching normally (I pick some random anime), you can try pressing F12 - or Inspect in your browser, and check the network tab, console tab, etc, if anything happens, screenshot it, I'll try to fix it 😃 .
![image](https://github.com/huy232/Unime/assets/59156109/5f3875c2-f9e6-4933-9131-d90d218cda0d)

**Comment by ILikeW** [comment]
understood

**Comment by ILikeW** [comment]
yeah its werid, i tried it on my phone(tried watching that time i got reincarnated as a slime) and on my laptop(demon slayer) and the player wouldnt play as you showed in your screenshot, it would just say "Loading Anime" not sure if its just on my end(my wifi).

**Comment by huy232** [comment]
Try to choose Zoro provider, may e Gogoanime provider has problems right now and can't load anime 😃

**Comment by ILikeW** [comment]
![Screenshot 2023-05-21 4 37 24 PM](https://github.com/huy232/Unime/assets/64869749/13251253-2a74-436c-9155-46cb1b98217d)

**Comment by huy232** [comment]
Zoro provider work for now, there's a provider select when you are at anime info page, you'll see it around here

![image](https://github.com/huy232/Unime/assets/59156109/7e4c9869-37a6-4afe-ac8c-ac7f39496abb)

![image](https://github.com/huy232/Unime/assets/59156109/acd67738-0f6e-4fc5-b317-432caddf4a59)

**Comment by ILikeW** [comment]
yeah it works, thanks
